# -*- coding: utf-8 -*-
"""GenAI_Competition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNVorLlzxFGgTaXL5-vzEVF9_xOeGKIa
"""

!pip install -q transformers datasets pillow matplotlib seaborn wordcloud

import os
import re
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from tqdm import tqdm
import torch
from transformers import pipeline, CLIPProcessor, CLIPModel, BlipProcessor, BlipForConditionalGeneration

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c gen-ai-competition
!unzip -q gen-ai-competition.zip -d data

test_dir = "data/data"

plt.figure(figsize=(15, 8))

image_files = [f for f in os.listdir(test_dir) if f.endswith(('.jpg', '.png', '.jpeg'))][:8]

for i, img_file in enumerate(image_files):
    img_path = os.path.join(test_dir, img_file)
    img = Image.open(img_path)

    plt.subplot(2, 4, i+1)
    plt.imshow(img)
    plt.title(img_file)
    plt.axis('off')

plt.tight_layout()
plt.show()

from transformers import Blip2Processor, Blip2ForConditionalGeneration

processor = Blip2Processor.from_pretrained("Salesforce/blip2-opt-2.7b")
model = Blip2ForConditionalGeneration.from_pretrained(
    "Salesforce/blip2-opt-2.7b",
    torch_dtype=torch.float16
).to("cuda")

test_dir = "data/data"

image_files = [f for f in os.listdir(test_dir) if f.lower().endswith(('.jpg', '.png', '.jpeg'))]
test_image_path = os.path.join(test_dir, image_files[0])

img = Image.open(test_image_path).convert("RGB")

plt.figure(figsize=(8, 6))
plt.imshow(img)
plt.title("Приклад картинки")
plt.axis('off')
plt.show()

prompt = "a photo of"
inputs = processor(images=img, text=prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        num_beams=8,
        min_new_tokens=15,
        max_new_tokens=60,
        length_penalty=1.3,
        repetition_penalty=1.2,
        early_stopping=True
    )

caption = processor.decode(outputs[0], skip_special_tokens=True)
print("Згенерований опис:")
print(caption)

results = []

for i, img_file in enumerate(tqdm(image_files[:10])):
    img_path = os.path.join(test_dir, img_file)
    img = Image.open(img_path).convert("RGB")
    img = img.resize((384, 384))

    prompt = "a photo of"
    inputs = processor(images=img, text=prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=8,
            min_new_tokens=15,
            max_new_tokens=60,
            length_penalty=1.3,
            repetition_penalty=1.2,
            early_stopping=True
        )

    caption = processor.decode(outputs[0], skip_special_tokens=True)

    results.append({
        'image': img_file,
        'caption': caption
    })

df_test = pd.DataFrame(results)
display(df_test)

image_files = [f for f in os.listdir(test_dir) if f.lower().endswith(('.jpg', '.png', '.jpeg'))]
image_files.sort()

captions_dict = {}

for img_file in tqdm(image_files):
    img_path = os.path.join(test_dir, img_file)
    img = Image.open(img_path).convert("RGB")

    prompt = "a photo of"
    inputs = processor(images=img, text=prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=8,
            min_new_tokens=15,
            max_new_tokens=60,
            length_penalty=1.3,
            repetition_penalty=1.2,
            early_stopping=True
        )

    caption = processor.decode(outputs[0], skip_special_tokens=True)
    captions_dict[img_file] = caption

df_captions = pd.DataFrame({
    'image': list(captions_dict.keys()),
    'caption': list(captions_dict.values())
})

display(df_captions.head(15))

df_captions.to_csv("captions_blip.csv", index=False)

clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to("cuda" if torch.cuda.is_available() else "cpu")
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

submission_rows = []
embedding_dim = 512

for img_file in tqdm(captions_dict.keys()):
    base_name = os.path.splitext(img_file)[0]
    caption = captions_dict[img_file]

    inputs = clip_processor(
        text=caption,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(clip_model.device)

    with torch.no_grad():
        text_features = clip_model.text_model(**inputs).pooler_output
        text_features = clip_model.text_projection(text_features)
        text_features = text_features / text_features.norm(dim=-1, keepdim=True)
        embedding = text_features.squeeze().cpu().numpy()

    for dim in range(embedding_dim):
        embedding_id = f"{base_name}_{dim}"
        submission_rows.append({
            "Embedding_id": embedding_id,
            "Embedding_value": float(embedding[dim])
        })

final_submission = pd.DataFrame(submission_rows)
final_submission.to_csv("submission.csv", index=False)

display(final_submission.head(10))

!kaggle competitions submit -c gen-ai-competition -f submission.csv -m "First submission - BLIP + CLIP baseline"

df_captions['caption_length'] = df_captions['caption'].apply(len)
df_captions['word_count'] = df_captions['caption'].apply(lambda x: len(x.split()))

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.histplot(df_captions['caption_length'], bins=20, kde=True)
plt.title('Довжина описів (символів)')
plt.xlabel('Кількість символів')

plt.subplot(1, 2, 2)
sns.histplot(df_captions['word_count'], bins=15, kde=True, color='orange')
plt.title('Кількість слів в описах')
plt.xlabel('Кількість слів')

plt.tight_layout()
plt.show()

all_text = " ".join(df_captions['caption'])

plt.figure(figsize=(10, 6))
wordcloud = WordCloud(width=800, height=400, background_color='white', colormap='viridis').generate(all_text)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud згенерованих описів', fontsize=16)
plt.show()

display(df_captions[['image', 'caption']].sample(8).reset_index(drop=True))